name: SBOM Security Gate

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  sbom:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate CycloneDX SBOM
        uses: anchore/sbom-action@v0
        with:
          path: .
          format: cyclonedx-json
          output-file: sbom-cyclonedx.json
          artifact-name: sbom-cyclonedx.json

  upload:
    needs: sbom    
    runs-on: self-hosted 

    steps:
      - name: Download SBOM artifact
        uses: actions/download-artifact@v4
        with:
          name: sbom-cyclonedx.json
          path: .

      - name: Upload SBOM to Dependency-Track
        uses: DependencyTrack/gh-upload-sbom@v3
        with:
          protocol: "http"
          serverHostname: ${{ secrets.DEPENDENCYTRACK_HOSTNAME }}
          port: "8081"
          apiKey: ${{ secrets.DEPENDENCYTRACK_APIKEY }}
          project: '9d5ae6e5-5d61-47b7-9470-048ed16d2168'
          bomFilename: "sbom-cyclonedx.json"
          
  security-gate:
      needs: upload
      runs-on: self-hosted
    
      steps:
        - name: Wait for Dependency-Track analysis
          shell: cmd
          run: powershell -ExecutionPolicy Bypass -Command "Write-Host 'Attente de lanalyse Dependency-Track (30 secondes)...'; Start-Sleep -Seconds 30"
        - name: Check Policy Violations
          id: check-violations
          shell: cmd
          run: >
            powershell -ExecutionPolicy Bypass -File scripts/check_policy.ps1
            -ProjectUuid '9d5ae6e5-5d61-47b7-9470-048ed16d2168'
            -DtHost '${{ secrets.DEPENDENCYTRACK_HOSTNAME }}'
            -DtPort '8081'
            -ApiKey '${{ secrets.DEPENDENCYTRACK_APIKEY }}'
