name: Generate a spdx SBOM

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  sbom:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate SPDX SBOM
        uses: anchore/sbom-action@v0
        with:
          path: .
          format: spdx
          output-file: kubernetes-spdx.json
          artifact-name: kubernetes-spdx.json
